# Generated by Django 5.0 on 2024-10-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_createpost_post_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_detail',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
