# Generated by Django 5.0 on 2024-10-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_post_detail_like'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_detail',
            old_name='like',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='post_detail',
            name='likedby',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='auth_app.user'),
        ),
    ]
